### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gongyang** [51web/hwcheck#1]
我使用hwcheck工具检测的时候报错 list index out of range，还有就是这个工具对于做了raid的硬盘，检测不到信息

**Comment by itxx00** [comment]
你的是dell哪个机型？ raid卡是哪个型号的？

## 

_Regards,_
_GaoYongwei_

2016-06-20 14:30 GMT+08:00 gongyang notifications@github.com:

**Comment by linuxhub** [comment]
`DELL R815`
check_vdisk修改增加如下:

<pre>
def check_vdisk():
          ...
        elif len(i) == 16:
            Layout = i[6].strip()
            Size = i[7].strip()
            Device_Name = i[8].strip()
            Bus_Protocol = i[9].strip()
            Media = i[10].strip()
</pre>

check_pdisk修改如下:

<pre>
def check_pdisk():
        ...
        if len(i) == 33:
            Device_Write_Cache = i[32].strip()
            Manufacture_Day = i[33].strip()
            Manufacture_Week = i[34].strip()
            Manufacture_Year = i[35].strip()
            SAS_Address = i[36].strip()
</pre>

**Comment by itxx00** [comment]
@linuxhub  感谢反馈，我目测了一下 check_vdisk这里似乎缺少i[5] 的定义？
check_pdisk这里判断长度是不是应该用大于等于？
你那边能否来一发PR  :-)

**Comment by linuxhub** [comment]
<pre>pdisks = ['0:0:0;Ok;Physical Disk 0:0:0;Online;Spun Up;SAS;HDD;Not Applicable;No;U440;Not Applicable;Not Applicable;Yes;No;Not Applicable;Not Applicable;Not Applicable;1,117.25 GB (1199638052864 bytes);1,117.25 GB (1199638052864 bytes);0.00 GB (0 bytes);No;HGST;HUC101212CSS600;KZG3YJ3D;TH0T6TWN1256735U167VA00;6.00 Gbps;6.00 Gbps;Not Applicable;05;22;2013;5000CCA01D072FB5', '0:0:1;Ok;Physical Disk 0:0:1;Online;Spun Up;SAS;HDD;Not Applicable;No;U440;Not Applicable;Not Applicable;Yes;No;Not Applicable;Not Applicable;Not Applicable;1,117.25 GB (1199638052864 bytes);1,117.25 GB (1199638052864 bytes);0.00 GB (0 bytes);No;HGST;HUC101212CSS600;KZG7S47D;TH0T6TWN1256735U1686A00;6.00 Gbps;6.00 Gbps;Not Applicable;05;22;2013;5000CCA01D0E15CD', '0:0:2;Ok;Physical Disk 0:0:2;Online;Spun Up;SAS;HDD;Not Applicable;No;U440;Not Applicable;Not Applicable;Yes;No;Not Applicable;Not Applicable;Not Applicable;1,117.25 GB (1199638052864 bytes);1,117.25 GB (1199638052864 bytes);0.00 GB (0 bytes);No;HGST;HUC101212CSS600;KZG3UL0D;TH0T6TWN1256735U168EA00;6.00 Gbps;6.00 Gbps;Not Applicable;05;22;2013;5000CCA01D06F491', '0:0:3;Ok;Physical Disk 0:0:3;Online;Spun Up;SAS;HDD;Not Applicable;No;U440;Not Applicable;Not Applicable;Yes;No;Not Applicable;Not Applicable;Not Applicable;1,117.25 GB (1199638052864 bytes);1,117.25 GB (1199638052864 bytes);0.00 GB (0 bytes);No;HGST;HUC101212CSS600;KZG2LGMD;TH0T6TWN1256735U168QA00;6.00 Gbps;6.00 Gbps;Not Applicable;05;22;2013;5000CCA01D04B855', '1:0:4;Ok;Physical Disk 1:0:4;Online;Spun Up;SAS;HDD;Not Applicable;No;U440;Not Applicable;Not Applicable;Yes;No;Not Applicable;Not Applicable;Not Applicable;1,117.25 GB (1199638052864 bytes);1,117.25 GB (1199638052864 bytes);0.00 GB (0 bytes);No;HGST;HUC101212CSS600;KZG32KTD;TH0T6TWN1256735U1699A00;6.00 Gbps;6.00 Gbps;Not Applicable;05;22;2013;5000CCA01D059B19', '1:0:5;Ok;Physical Disk 1:0:5;Online;Spun Up;SAS;HDD;Not Applicable;No;U440;Not Applicable;Not Applicable;Yes;No;Not Applicable;Not Applicable;Not Applicable;1,117.25 GB (1199638052864 bytes);1,117.25 GB (1199638052864 bytes);0.00 GB (0 bytes);No;HGST;HUC101212CSS600;KZG3UE2D;TH0T6TWN1256735U167YA00;6.00 Gbps;6.00 Gbps;Not Applicable;05;22;2013;5000CCA01D06F22D']
</pre>

**Comment by linuxhub** [comment]
<pre>
disks = ['0;Ok;Virtual Disk 0;Ready;Not Assigned;No;RAID-5;5,586.25 GB (5998190264320 bytes);/dev/sda;SAS;HDD;Adaptive Read Ahead;Write Back;Not Applicable;64 KB;Disabled']
</pre>
